### PR TITLE
Updated QMK to include latest features and fixed resulting bugs

### PR DESCRIPTION
**Pull request by xp-dv**
## Purpose

This is for new GMMK 2 owners to have a working, updated version of QMK without the wait for the next complete official release. I know these exact features are in development in other branches of this repo. This is to prevent frustration for new GMMK 2 owners. I started these fixes because I was frustrated and confused that Caps Word didn't work on my new GMMK 2 96% despite being listed as a core feature on QMK's documentation.

## Description
Merged _qmk/qmk_firmware_ (most recent version as of 5 June, 2022) and _GloriousThrall/qmk_firmware_ and fixed merge conflicts (all trivial).

Attempted to compile after merge was successful but got this error: (_gmmk/gmmk2/p96/ansi: led_config: ansi.c: Unable to parse g_led_config matrix data_).

Error fixed by reformatting the led config array in _gmmk/gmmk2/p96/ansi/ansi.c_ , _gmmk/gmmk2/p96/iso/iso.c_ , _gmmk/gmmk2/p65/ansi/ansi.c_ , and _gmmk/gmmk2/p65/ansi/ansi.c_. (See commits for additional info)

Changed SPI mode back to 0 or else RGB will not turn on. (It was set to 3 temporarily as a bug fix by qmk/qmk-firmware)

Found compile error in _gmmk/gmmk2/p96/iso/iso.c_. Fixed by deleting code I believe was copy-pasted in by mistake (Erroneous code is found in https://github.com/GloriousThrall/qmk_firmware/blob/gmmk_v2_keyboard/keyboards/gmmk/gmmk2/p96/iso/iso.c, but not in https://github.com/GloriousThrall/qmk_firmware/blob/glorious_gmmk2/keyboards/gmmk/gmmk2/p96/iso/iso.c)

QMK compile successful and no errors for all possible firmware combinations (96, 65, ansi, iso). Flash to new GMMK 2 96% keyboard successful and functional for both ansi and iso.

The changes made by myself are what is listed above. The rest of the commits and changes are just what was carried over from the merge.

**Note: I do not own a GMMK 2 65%, so I cannot test if flash is successful on that platform. However, given that I only made the changes above and all compiling was successful, there should be no issue.**
**Note: I ran into problems with my repo and PRing so the commit history was manually edited/organized.**

This would not have been possible if it weren't for @filterpaper. HUGE thank you for the help.

## Types of Changes

- [x] Core
- [x] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [x] Documentation

## Issues Fixed or Closed by This PR

* No _outside_ issues fixed or closed by me.

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by maxmousee** [comment]
I tested this on my GMMK 2 65% ANSI and it seems to be working fine! :)

**Comment by maxmousee** [comment]
FYI @GR4NDIVI4ST3R I was able to flash VIA using this as well! Great job :)

**Comment by ro8inmorgan** [comment]
GMMK2 compact RGB does not turn back on after disconnecting USB on latest commit on branch gmmk2_p65

**Comment by maxmousee** [comment]
> GMMK2 compact RGB does not turn back on after disconnecting USB on latest commit on branch gmmk2_p65

For me, it works fine:)

**Comment by ro8inmorgan** [comment]
> > GMMK2 compact RGB does not turn back on after disconnecting USB on latest commit on branch gmmk2_p65
> 
> For me, it works fine:)

In case you have other issues I forked this git with my fixes added on top of it like correct RGB, eeprom saving and underglow aligned correctly
https://github.com/ro8inmorgan/qmk_firmware

**Comment by maxmousee** [comment]
> > > GMMK2 compact RGB does not turn back on after disconnecting USB on latest commit on branch gmmk2_p65
> > 
> > 
> > For me, it works fine:)
> 
> In case you have other issues I forked this git with my fixes added on top of it like correct RGB, eeprom saving and underglow aligned correctly https://github.com/ro8inmorgan/qmk_firmware

Thank you very much! :)

**Comment by ro8inmorgan** [comment]
> > > > GMMK2 compact RGB does not turn back on after disconnecting USB on latest commit on branch gmmk2_p65
> > > 
> > > 
> > > For me, it works fine:)
> > 
> > 
> > In case you have other issues I forked this git with my fixes added on top of it like correct RGB, eeprom saving and underglow aligned correctly https://github.com/ro8inmorgan/qmk_firmware
> 
> Thank you very much! :)

Your welcome!  Make sure to flash it with the glorious_gmmk2 branch as per instructions on the glorious site. There are all my fixes merged. I also enabled more effects and removed one effect that crashes the board.

**Comment by maxmousee** [comment]
> > > > > GMMK2 compact RGB does not turn back on after disconnecting USB on latest commit on branch gmmk2_p65
> > > > 
> > > > 
> > > > For me, it works fine:)
> > > 
> > > 
> > > In case you have other issues I forked this git with my fixes added on top of it like correct RGB, eeprom saving and underglow aligned correctly https://github.com/ro8inmorgan/qmk_firmware
> > 
> > 
> > Thank you very much! :)
> 
> Your welcome! Make sure to flash it with the glorious_gmmk2 branch as per instructions on the glorious site. There are all my fixes merged. I also enabled more effects and removed one effect that crashes the board.

Do you know if there's a way to get the correct via design for it? Currently it's using the GMMK Pro design and it's so wrong it's barely usable for reassigning any key :(

**Comment by ro8inmorgan** [comment]
> > > > > > GMMK2 compact RGB does not turn back on after disconnecting USB on latest commit on branch gmmk2_p65
> > > > > 
> > > > > 
> > > > > For me, it works fine:)
> > > > 
> > > > 
> > > > In case you have other issues I forked this git with my fixes added on top of it like correct RGB, eeprom saving and underglow aligned correctly https://github.com/ro8inmorgan/qmk_firmware
> > > 
> > > 
> > > Thank you very much! :)
> > 
> > 
> > Your welcome! Make sure to flash it with the glorious_gmmk2 branch as per instructions on the glorious site. There are all my fixes merged. I also enabled more effects and removed one effect that crashes the board.
> 
> Do you know if there's a way to get the correct via design for it? Currently it's using the GMMK Pro design and it's so wrong it's barely usable for reassigning any key :(

Haven't looked much into VIA to be honest. I  think you can make your own json key file for it.  I run all my customisations from code. To be honest its not too hard just look into a few keymaps tutorials. You will be happy you did,.

**Comment by xp-dv** [comment]
@ro8inmorgan did you pull from the branch on my actual repo (glorious_gmmk2 branch) or did you just copy the changes? I can't really tell what you changed differently. All I did was pull from master and fix the layout issues. There's not really much I could have messed up that wasn't already messed up from the start.

**Comment by ro8inmorgan** [comment]
> @ro8inmorgan did you pull from the branch on my actual repo (glorious_gmmk2 branch) or did you just copy the changes? I can't really tell what you changed differently. All I did was pull from master and fix the layout issues. There's not really much I could have messed up that wasn't already messed up from the start.

@GR4NDIVI4ST3R 
In this repo the gmmk2_p65 branch the RGB works(altough underglow is wrong) but somehow the EEPROM code is messed up. RGB works after flashing but once disconnecting usb and reconnecting it doesn't work again. The glorious_gmmk2 branch has all messed up RGB like for the ESC key red is assigned to driver 1 and green and blue to driver 0 etc. 

I forked this repository and mixed both branches to create a working version. Also I fixed the underglow plus removed the fractal effect which was causing a crash. Also enabled the reactive effects by default. 
I don't know about the other boards, I'm specifically targeting the GMMK2 Compact as that's the one I have.

**Comment by xp-dv** [comment]
@ro8inmorgan 
So you're saying that *my pull request* also has this issue? Remember you
are commenting on *my specific pull request, NOT other branches*. Only
comment here if it's a problem that *ONLY exists on MY branch*. If it
persists on BOTH branches, then it's not a problem with *my pull request
(i.e. my **specific* *changes)*, it's a problem with the branch I cloned
from. Let me know which is the case. I'm not assuming, it's just really
important to know the difference.

**Comment by guilleortas** [comment]
Hello @ro8inmorgan, I tested your fork on the glorious_gmmk2 branch and everything seems to be working, but VIA detects my GMMK 2 65% ISO as a GMMK Pro, even after loading the appropriate design file, so nothing matches in the layout. I have posted a [comment](https://github.com/qmk/qmk_firmware/pull/16436#issuecomment-1233007193) on a merged PR on the official QMK repo with the same results. Any ideas?

**Comment by xp-dv** [comment]
@guilleortas and everyone who has commented so far, please **do not post any further communication here**, unless it relates to **this specific pull request**. Problems with the parent branch should **not** be discussed here. The VIA issue is one such problem. I appreciate everyone trying to fix GMMK's broken firmware, but that is not a problem with my pull request. **This kind of thing gets pull requests denied.**

**Comment by guilleortas** [comment]
@GR4NDIVI4ST3R my comment was specific about this PR, unless I didn't understand correctly. Peer review is the whole point of open source, if it doesn't work for the majority the PR should be denied

**Pull request closed without merging**
